In [1]:
import pandas as pd
import numpy as np
from sklearn.feature_extraction.text import TfidfVectorizer

In [2]:
df = pd.read_csv('L:\\Workspace\\Models\\Review Sent Analyzer And Summarizer\\cleaned_reviews_data_20_apps.csv')

In [3]:
df['review_ratings'] = df['review_ratings'].replace('neu', 'pos')
df['review_ratings'].value_counts()

review_ratings
pos    83795
neg    45246
Name: count, dtype: int64

In [4]:
X = df['content']
y = df['review_ratings']

In [5]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(X, y, test_size=0.35, random_state=42)

In [6]:
tfidf = TfidfVectorizer()
x_train_vec = tfidf.fit_transform(x_train)
x_test_vec = tfidf.transform(x_test)

In [9]:
from sklearn.naive_bayes import MultinomialNB, ComplementNB
from sklearn.linear_model import LogisticRegression, SGDClassifier
from sklearn.svm import LinearSVC
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

def print_scores_new():
    models = {
        "nb": MultinomialNB(),
        "cnb": ComplementNB(),
        "logreg": LogisticRegression(max_iter=1000),
        "svm": LinearSVC(),
        "sgd": SGDClassifier()
    }
    for k in models.keys():
        model = models[k]
        model.fit(x_train_vec, y_train)
        print("Model - ", k)
        preds = model.predict(x_test_vec)
        acc = accuracy_score(y_test,preds)
        print(f"Accuracy = {acc}")
        print("Confusion Matrix:")
        print(confusion_matrix(y_test,preds))
        print("\n Classification Report - ")
        print(classification_report(y_test,preds))

In [10]:
print_scores_new()

Model -  nb
Accuracy = 0.8448798848666003
Confusion Matrix:
[[11550  4159]
 [ 2847 26609]]

 Classification Report - 
              precision    recall  f1-score   support

         neg       0.80      0.74      0.77     15709
         pos       0.86      0.90      0.88     29456

    accuracy                           0.84     45165
   macro avg       0.83      0.82      0.83     45165
weighted avg       0.84      0.84      0.84     45165

Model -  cnb
Accuracy = 0.8101184545555187
Confusion Matrix:
[[13729  1980]
 [ 6596 22860]]

 Classification Report - 
              precision    recall  f1-score   support

         neg       0.68      0.87      0.76     15709
         pos       0.92      0.78      0.84     29456

    accuracy                           0.81     45165
   macro avg       0.80      0.83      0.80     45165
weighted avg       0.84      0.81      0.81     45165

Model -  logreg
Accuracy = 0.857212443263589
Confusion Matrix:
[[11947  3762]
 [ 2687 26769]]

 Classificatio

In [11]:
import joblib

In [12]:
joblib.dump(tfidf, "L:\\Workspace\\Models\\Review Sent Analyzer And Summarizer\\tfidf_vectorizer.joblib")
lr = LogisticRegression(max_iter=1000)
lr.fit(x_train_vec, y_train)
joblib.dump(lr, "L:\\Workspace\\Models\\Review Sent Analyzer And Summarizer\\LogisticRegression.joblib")

['L:\\Workspace\\Models\\Review Sent Analyzer And Summarizer\\LogisticRegression.joblib']

You can get them like this - 

tfidf = joblib.load("models/tfidf_vectorizer.joblib")

logreg = joblib.load("models/sentiment_logreg.joblib")

Forgot the save data - 

In [13]:
df.to_csv('L:\\Workspace\\Models\\Review Sent Analyzer And Summarizer\\review_data_binary.csv' , index=False)

### Oops, forgot to create the pipeline

In [14]:
from sklearn.pipeline import Pipeline

In [15]:
pipeline = Pipeline(steps=[("TFIDFVectorizer", tfidf), ("LogisticRegression", lr))]

TypeError: Pipeline.__init__() missing 1 required positional argument: 'steps'